// Data surah lengkap (114 surah)
export const surahs = [
  { id: 1, name: 'Al-Fatihah', arabic: 'الفاتحة', ayat: 7, juz: '1', type: 'Makkiyah' },
  { id: 2, name: 'Al-Baqarah', arabic: 'البقرة', ayat: 286, juz: '1-3', type: 'Madaniyah' },
  { id: 3, name: 'Ali Imran', arabic: 'آل عمران', ayat: 200, juz: '3-4', type: 'Madaniyah' },
  { id: 4, name: 'An-Nisa', arabic: 'النساء', ayat: 176, juz: '4-6', type: 'Madaniyah' },
  { id: 5, name: 'Al-Maidah', arabic: 'المائدة', ayat: 120, juz: '6-7', type: 'Madaniyah' },
  { id: 6, name: "Al-An'am", arabic: 'الأنعام', ayat: 165, juz: '7-8', type: 'Makkiyah' },
  { id: 7, name: "Al-A'raf", arabic: 'الأعراف', ayat: 206, juz: '8-9', type: 'Makkiyah' },
  { id: 8, name: 'Al-Anfal', arabic: 'الأنفال', ayat: 75, juz: '9-10', type: 'Madaniyah' },
  { id: 9, name: 'At-Taubah', arabic: 'التوبة', ayat: 129, juz: '10-11', type: 'Madaniyah' },
  { id: 10, name: 'Yunus', arabic: 'يونس', ayat: 109, juz: '11', type: 'Makkiyah' },

  { id: 11, name: 'Hud', arabic: 'هود', ayat: 123, juz: '11-12', type: 'Makkiyah' },
  { id: 12, name: 'Yusuf', arabic: 'يوسف', ayat: 111, juz: '12', type: 'Makkiyah' },
  { id: 13, name: "Ar-Ra'd", arabic: 'الرعد', ayat: 43, juz: '13', type: 'Madaniyah' },
  { id: 14, name: 'Ibrahim', arabic: 'ابراهيم', ayat: 52, juz: '13', type: 'Makkiyah' },
  { id: 15, name: 'Al-Hijr', arabic: 'الحجر', ayat: 99, juz: '14', type: 'Makkiyah' },
  { id: 16, name: 'An-Nahl', arabic: 'النحل', ayat: 128, juz: '14', type: 'Makkiyah' },
  { id: 17, name: 'Al-Isra', arabic: 'الإسراء', ayat: 111, juz: '15', type: 'Makkiyah' },
  { id: 18, name: 'Al-Kahf', arabic: 'الكهف', ayat: 110, juz: '15-16', type: 'Makkiyah' },
  { id: 19, name: 'Maryam', arabic: 'مريم', ayat: 98, juz: '16', type: 'Makkiyah' },
  { id: 20, name: 'Ta-Ha', arabic: 'طه', ayat: 135, juz: '16', type: 'Makkiyah' },

  { id: 21, name: 'Al-Anbiya', arabic: 'الأنبياء', ayat: 112, juz: '17', type: 'Makkiyah' },
  { id: 22, name: 'Al-Hajj', arabic: 'الحج', ayat: 78, juz: '17-18', type: 'Madaniyah' },
  { id: 23, name: 'Al-Muminun', arabic: 'المؤمنون', ayat: 118, juz: '18', type: 'Makkiyah' },
  { id: 24, name: 'An-Nur', arabic: 'النور', ayat: 64, juz: '18', type: 'Madaniyah' },
  { id: 25, name: 'Al-Furqan', arabic: 'الفرقان', ayat: 77, juz: '18-19', type: 'Makkiyah' },
  { id: 26, name: "Ash-Shu'ara", arabic: 'الشعراء', ayat: 227, juz: '19', type: 'Makkiyah' },
  { id: 27, name: 'An-Naml', arabic: 'النمل', ayat: 93, juz: '19-20', type: 'Makkiyah' },
  { id: 28, name: 'Al-Qasas', arabic: 'القصص', ayat: 88, juz: '20', type: 'Makkiyah' },
  { id: 29, name: 'Al-Ankabut', arabic: 'العنكبوت', ayat: 69, juz: '20-21', type: 'Makkiyah' },
  { id: 30, name: 'Ar-Rum', arabic: 'الروم', ayat: 60, juz: '21', type: 'Makkiyah' },

  { id: 31, name: 'Luqman', arabic: 'لقمان', ayat: 34, juz: '21', type: 'Makkiyah' },
  { id: 32, name: 'As-Sajdah', arabic: 'السجدة', ayat: 30, juz: '21', type: 'Makkiyah' },
  { id: 33, name: 'Al-Ahzab', arabic: 'الأحزاب', ayat: 73, juz: '21-22', type: 'Madaniyah' },
  { id: 34, name: 'Saba', arabic: 'سبإ', ayat: 54, juz: '22', type: 'Makkiyah' },
  { id: 35, name: 'Fatir', arabic: 'فاطر', ayat: 45, juz: '22', type: 'Makkiyah' },
  { id: 36, name: 'Yasin', arabic: 'يس', ayat: 83, juz: '22-23', type: 'Makkiyah' },
  { id: 37, name: 'As-Saffat', arabic: 'الصافات', ayat: 182, juz: '23', type: 'Makkiyah' },
  { id: 38, name: 'Sad', arabic: 'ص', ayat: 88, juz: '23', type: 'Makkiyah' },
  { id: 39, name: 'Az-Zumar', arabic: 'الزمر', ayat: 75, juz: '23-24', type: 'Makkiyah' },
  { id: 40, name: 'Ghafir', arabic: 'غافر', ayat: 85, juz: '24', type: 'Makkiyah' },

  { id: 41, name: 'Fussilat', arabic: 'فصلت', ayat: 54, juz: '24-25', type: 'Makkiyah' },
  { id: 42, name: 'Ash-Shura', arabic: 'الشورى', ayat: 53, juz: '25', type: 'Makkiyah' },
  { id: 43, name: 'Az-Zukhruf', arabic: 'الزخرف', ayat: 89, juz: '25', type: 'Makkiyah' },
  { id: 44, name: 'Ad-Dukhan', arabic: 'الدخان', ayat: 59, juz: '25', type: 'Makkiyah' },
  { id: 45, name: 'Al-Jasiyah', arabic: 'الجاثية', ayat: 37, juz: '25', type: 'Makkiyah' },
  { id: 46, name: 'Al-Ahqaf', arabic: 'الأحقاف', ayat: 35, juz: '26', type: 'Makkiyah' },
  { id: 47, name: 'Muhammad', arabic: 'محمد', ayat: 38, juz: '26', type: 'Madaniyah' },
  { id: 48, name: 'Al-Fath', arabic: 'الفتح', ayat: 29, juz: '26', type: 'Madaniyah' },
  { id: 49, name: 'Al-Hujurat', arabic: 'الحجرات', ayat: 18, juz: '26', type: 'Madaniyah' },
  { id: 50, name: 'Qaf', arabic: 'ق', ayat: 45, juz: '26', type: 'Makkiyah' },

  { id: 51, name: 'Az-Zariyat', arabic: 'الذاريات', ayat: 60, juz: '26-27', type: 'Makkiyah' },
  { id: 52, name: 'At-Tur', arabic: 'الطور', ayat: 49, juz: '27', type: 'Makkiyah' },
  { id: 53, name: 'An-Najm', arabic: 'النجم', ayat: 62, juz: '27', type: 'Makkiyah' },
  { id: 54, name: 'Al-Qamar', arabic: 'القمر', ayat: 55, juz: '27', type: 'Makkiyah' },
  { id: 55, name: 'Ar-Rahman', arabic: 'الرحمن', ayat: 78, juz: '27', type: 'Madaniyah' },
  { id: 56, name: "Al-Waqi'ah", arabic: 'الواقعة', ayat: 96, juz: '27', type: 'Makkiyah' },
  { id: 57, name: 'Al-Hadid', arabic: 'الحديد', ayat: 29, juz: '27', type: 'Madaniyah' },
  { id: 58, name: 'Al-Mujadilah', arabic: 'المجادلة', ayat: 22, juz: '28', type: 'Madaniyah' },
  { id: 59, name: 'Al-Hashr', arabic: 'الحشر', ayat: 24, juz: '28', type: 'Madaniyah' },
  { id: 60, name: 'Al-Mumtahanah', arabic: 'الممتحنة', ayat: 13, juz: '28', type: 'Madaniyah' },

  { id: 61, name: 'As-Saff', arabic: 'الصف', ayat: 14, juz: '28', type: 'Madaniyah' },
  { id: 62, name: "Al-Jumu'ah", arabic: 'الجمعة', ayat: 11, juz: '28', type: 'Madaniyah' },
  { id: 63, name: 'Al-Munafiqun', arabic: 'المنافقون', ayat: 11, juz: '28', type: 'Madaniyah' },
  { id: 64, name: 'At-Taghabun', arabic: 'التغابن', ayat: 18, juz: '28', type: 'Madaniyah' },
  { id: 65, name: 'At-Talaq', arabic: 'الطلاق', ayat: 12, juz: '28', type: 'Madaniyah' },
  { id: 66, name: 'At-Tahrim', arabic: 'التحريم', ayat: 12, juz: '28', type: 'Madaniyah' },
  { id: 67, name: 'Al-Mulk', arabic: 'الملك', ayat: 30, juz: '29', type: 'Makkiyah' },
  { id: 68, name: 'Al-Qalam', arabic: 'القلم', ayat: 52, juz: '29', type: 'Makkiyah' },
  { id: 69, name: 'Al-Haqqah', arabic: 'الحاقة', ayat: 52, juz: '29', type: 'Makkiyah' },
  { id: 70, name: "Al-Ma'arij", arabic: 'المعارج', ayat: 44, juz: '29', type: 'Makkiyah' },

  { id: 71, name: 'Nuh', arabic: 'نوح', ayat: 28, juz: '29', type: 'Makkiyah' },
  { id: 72, name: 'Al-Jinn', arabic: 'الجن', ayat: 28, juz: '29', type: 'Makkiyah' },
  { id: 73, name: 'Al-Muzzammil', arabic: 'المزمل', ayat: 20, juz: '29', type: 'Makkiyah' },
  { id: 74, name: 'Al-Muddathir', arabic: 'المدثر', ayat: 56, juz: '29', type: 'Makkiyah' },
  { id: 75, name: 'Al-Qiyamah', arabic: 'القيامة', ayat: 40, juz: '29', type: 'Makkiyah' },
  { id: 76, name: 'Al-Insan', arabic: 'الانسان', ayat: 31, juz: '29', type: 'Madaniyah' },
  { id: 77, name: 'Al-Mursalat', arabic: 'المرسلات', ayat: 50, juz: '29', type: 'Makkiyah' },
  { id: 78, name: 'An-Naba', arabic: 'النبأ', ayat: 40, juz: '30', type: 'Makkiyah' },
  { id: 79, name: "An-Nazi'at", arabic: 'النازعات', ayat: 46, juz: '30', type: 'Makkiyah' },
  { id: 80, name: 'Abasa', arabic: 'عبس', ayat: 42, juz: '30', type: 'Makkiyah' },

  { id: 81, name: 'At-Takwir', arabic: 'التكوير', ayat: 29, juz: '30', type: 'Makkiyah' },
  { id: 82, name: 'Al-Infitar', arabic: 'الإنفطار', ayat: 19, juz: '30', type: 'Makkiyah' },
  { id: 83, name: 'Al-Mutaffifin', arabic: 'المطففين', ayat: 36, juz: '30', type: 'Makkiyah' },
  { id: 84, name: 'Al-Inshiqaq', arabic: 'الإنشقاق', ayat: 25, juz: '30', type: 'Makkiyah' },
  { id: 85, name: 'Al-Buruj', arabic: 'البروج', ayat: 22, juz: '30', type: 'Makkiyah' },
  { id: 86, name: 'At-Tariq', arabic: 'الطارق', ayat: 17, juz: '30', type: 'Makkiyah' },
  { id: 87, name: "Al-A'la", arabic: 'الأعلى', ayat: 19, juz: '30', type: 'Makkiyah' },
  { id: 88, name: 'Al-Ghashiyah', arabic: 'الغاشية', ayat: 26, juz: '30', type: 'Makkiyah' },
  { id: 89, name: 'Al-Fajr', arabic: 'الفجر', ayat: 30, juz: '30', type: 'Makkiyah' },
  { id: 90, name: 'Al-Balad', arabic: 'البلد', ayat: 20, juz: '30', type: 'Makkiyah' },

  { id: 91, name: 'Ash-Shams', arabic: 'الشمس', ayat: 15, juz: '30', type: 'Makkiyah' },
  { id: 92, name: 'Al-Lail', arabic: 'الليل', ayat: 21, juz: '30', type: 'Makkiyah' },
  { id: 93, name: 'Ad-Duha', arabic: 'الضحى', ayat: 11, juz: '30', type: 'Makkiyah' },
  { id: 94, name: 'Ash-Sharh', arabic: 'الشرح', ayat: 8, juz: '30', type: 'Makkiyah' },
  { id: 95, name: 'At-Tin', arabic: 'التين', ayat: 8, juz: '30', type: 'Makkiyah' },
  { id: 96, name: "Al-'Alaq", arabic: 'العلق', ayat: 19, juz: '30', type: 'Makkiyah' },
  { id: 97, name: 'Al-Qadr', arabic: 'القدر', ayat: 5, juz: '30', type: 'Makkiyah' },
  { id: 98, name: 'Al-Bayyinah', arabic: 'البينة', ayat: 8, juz: '30', type: 'Madaniyah' },
  { id: 99, name: 'Az-Zalzalah', arabic: 'الزلزلة', ayat: 8, juz: '30', type: 'Madaniyah' },
  { id: 100, name: "Al-'Adiyat", arabic: 'العاديات', ayat: 11, juz: '30', type: 'Makkiyah' },

  { id: 101, name: "Al-Qari'ah", arabic: 'القارعة', ayat: 11, juz: '30', type: 'Makkiyah' },
  { id: 102, name: 'At-Takathur', arabic: 'التكاثر', ayat: 8, juz: '30', type: 'Makkiyah' },
  { id: 103, name: "Al-'Asr", arabic: 'العصر', ayat: 3, juz: '30', type: 'Makkiyah' },
  { id: 104, name: 'Al-Humazah', arabic: 'الهمزة', ayat: 9, juz: '30', type: 'Makkiyah' },
  { id: 105, name: 'Al-Fil', arabic: 'الفيل', ayat: 5, juz: '30', type: 'Makkiyah' },
  { id: 106, name: 'Quraysh', arabic: 'قريش', ayat: 4, juz: '30', type: 'Makkiyah' },
  { id: 107, name: "Al-Ma'un", arabic: 'الماعون', ayat: 7, juz: '30', type: 'Makkiyah' },
  { id: 108, name: 'Al-Kawthar', arabic: 'الكوثر', ayat: 3, juz: '30', type: 'Makkiyah' },
  { id: 109, name: 'Al-Kafirun', arabic: 'الكافرون', ayat: 6, juz: '30', type: 'Makkiyah' },
  { id: 110, name: 'An-Nasr', arabic: 'النصر', ayat: 3, juz: '30', type: 'Madaniyah' },

  { id: 111, name: 'Al-Lahab', arabic: 'المسد', ayat: 5, juz: '30', type: 'Makkiyah' },
  { id: 112, name: 'Al-Ikhlas', arabic: 'الإخلاص', ayat: 4, juz: '30', type: 'Makkiyah' },
  { id: 113, name: 'Al-Falaq', arabic: 'الفلق', ayat: 5, juz: '30', type: 'Makkiyah' },
  { id: 114, name: 'An-Nas', arabic: 'الناس', ayat: 6, juz: '30', type: 'Makkiyah' }
];

  
export const juzRanges = {
  1: 'Al-Fatihah 1 - Al-Baqarah 141',
  2: 'Al-Baqarah 142 - Al-Baqarah 252',
  3: 'Al-Baqarah 253 - Ali Imran 92',
  4: 'Ali Imran 93 - An-Nisa 23',
  5: 'An-Nisa 24 - An-Nisa 147',
  6: 'An-Nisa 148 - Al-Maidah 81',
  7: 'Al-Maidah 82 - Al-Anam 110',
  8: "Al-Anam 111 - Al-A'raf 87",
  9: "Al-A'raf 88 - Al-Anfal 40",
  10: 'Al-Anfal 41 - At-Taubah 92',
  11: 'At-Taubah 93 - Hud 5',
  12: 'Hud 6 - Yusuf 52',
  13: 'Yusuf 53 - Ibrahim 52',
  14: 'Al-Hijr 1 - An-Nahl 128',
  15: 'Al-Isra 1 - Al-Kahf 74',
  16: 'Al-Kahf 75 - Ta Ha 135',
  17: 'Al-Anbiya 1 - Al-Hajj 78',
  18: 'Al-Muminun 1 - Al-Furqan 20',
  19: 'Al-Furqan 21 - An-Naml 55',
  20: 'An-Naml 56 - Al-Ankabut 45',
  21: 'Al-Ankabut 46 - Al-Ahzab 30',
  22: 'Al-Ahzab 31 - Yasin 27',
  23: 'Yasin 28 - Az-Zumar 31',
  24: 'Az-Zumar 32 - Fussilat 46',
  25: 'Fussilat 47 - Al-Jasiyah 37',
  26: 'Al-Ahqaf 1 - Az-Zariyat 30',
  27: 'Az-Zariyat 31 - Al-Hadid 29',
  28: 'Al-Mujadilah 1 - At-Tahrim 12',
  29: 'Al-Mulk 1 - Al-Mursalat 50',
  30: 'An-Naba 1 - An-Nas 6'
};
